name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIAYEKP5SMSWLPGQDHE }}
          AWS_SECRET_ACCESS_KEY: ${{ +DAKVsOtTGE0UVzv4rqYHRNim2m/npBSSEla8Zm9 }}
        run: |
          aws s3 sync ./dist s3://your-bucket-name --delete
